.vscode/settings.json
ratatoskr/app/models.py
ratatoskr/app/pages/index.html
ratatoskr/ratatoskr/settings.py
ratatoskr/ratatoskr/urls.py

Currently blocked on the developer account thing, but once we get an account it should be smooth sailing!

Setup Google OAuth

---

ratatoskr/app/templates/app/pages/index.html
ratatoskr/ratatoskr/urls.py

A very bodgey fix for #15. Might have to come back to this later, since this implementation MAY not be best practice...

Bodgey attempt at only using google auth

---

ratatoskr/app/templates/app/components/login_button.html
ratatoskr/app/templates/app/components/logout_button.html
ratatoskr/app/templates/app/layouts/base.html
ratatoskr/app/templates/app/pages/create_schedule.html
ratatoskr/app/templates/app/pages/index.html
ratatoskr/app/urls.py
ratatoskr/app/views.py

Still waiting on #39 to display these schedules. Might make a page later.

Schedule submits to database, Web design improvements

---

ratatoskr/app/templates/app/components/schedule_card.html
ratatoskr/app/templates/app/layouts/base.html
ratatoskr/app/templatetags/components.py

Started the scheduling card, need timeslots

Scheduling card

---

ratatoskr/app/templates/app/components/schedule_card.html
ratatoskr/app/templatetags/components.py
ratatoskr/app/templatetags/filters.py

That was completely unneccessary

Schedule card now takes schedule directly

---

ratatoskr/app/templates/app/components/timeslot_date.html
ratatoskr/app/templates/app/components/timeslot_time.html
ratatoskr/app/templates/app/pages/schedule.html
ratatoskr/app/templates/app/pages/schedule_day.html
ratatoskr/app/templatetags/components.py

timeslot_date and timeslot_time implemented

---

ratatoskr/app/templates/app/components/timeslot_time.html
ratatoskr/app/templates/app/pages/schedule_day.html

Timeslot time component 

---

ratatoskr/app/templates/app/layouts/base.html
ratatoskr/app/templates/app/layouts/schedule_base.html
ratatoskr/app/templates/app/pages/schedule.html
ratatoskr/app/templates/app/pages/schedule_day.html
ratatoskr/app/urls.py
ratatoskr/app/views.py
ratatoskr/static/scss/app/link-disable.scss
ratatoskr/static/scss/style.scss

Schedule locking, schedule editing improvements

---

ratatoskr/app/templates/app/layouts/base.html
ratatoskr/app/templates/app/layouts/schedule_listing.html

Designated block tag for scripts

---

ratatoskr/app/calendarutil.py
ratatoskr/app/forms.py
ratatoskr/app/templates/app/layouts/schedule_base.html
ratatoskr/app/templates/app/pages/reservations_view.html
ratatoskr/app/templates/app/pages/reservations_view_schedule.html
ratatoskr/app/templates/app/pages/reserve_timeslot.html
ratatoskr/app/templates/app/pages/schedule.html
ratatoskr/app/templates/app/pages/schedule_day.html
ratatoskr/app/templates/app/pages/schedules.html
ratatoskr/app/templatetags/components.py
ratatoskr/app/templatetags/filters.py
ratatoskr/app/urls.py
ratatoskr/app/views.py

This handles issue #105, allowing users to view reservations by schedule and by individual timeslot. Also handles issue #91, with a new indicator for full timeslots.

Reservation viewing and management

---

ratatoskr/app/templates/app/layouts/base.html
ratatoskr/app/templates/app/pages/create_timeslots.html

Refactor Timeslot Form, added subtitle 

---

ratatoskr/app/models.py
ratatoskr/app/templates/app/pages/schedule.html

Add link to Google Calendaron schedule

---

ratatoskr/app/templates/app/components/schedule_card.html
ratatoskr/app/templates/app/layouts/schedule_base.html
ratatoskr/app/templates/app/pages/schedule_edit.html
ratatoskr/app/templatetags/filters.py

At @leboeufj 's suggestion, TinyMCE has been added to the schedule description editor.

Added TinyMCE Support to Schedule Descriptions

---

ratatoskr/app/templates/app/pages/help.html

The help page now has some topics and a bit more of a structure for future use.

Help Page Progress

---

ratatoskr/app/templates/app/pages/contact.html

Will add the messaging form's functionality tomorrow

Improved contact page

---

Pipfile.lock
ratatoskr/app/templates/app/components/schedule_card.html
ratatoskr/app/templates/app/layouts/schedule_base.html
ratatoskr/app/templates/app/layouts/schedule_listing.html
ratatoskr/app/templates/app/pages/create_schedule.html
ratatoskr/app/templates/app/pages/index.html
ratatoskr/app/templates/app/pages/schedule.html
ratatoskr/app/templates/app/pages/schedule_day.html
ratatoskr/app/templates/app/pages/schedules.html
ratatoskr/static/scss/app/animated-arrow-button.scss
ratatoskr/static/scss/style.scss

I went through the app and ran lighthouse and fixed accessibility issues

Various Improvements and tweaks

---

Pipfile
Pipfile.lock

- readme
- Use dollar sign
- Ignore Pipfile.lock
- Add some dependencies
- Uncommit pipfile lock
- app
- Some base files stuff
- Correct readme
- Imported Bootstrap
- Configure some oauth settings
- oauth views
- Templates
- Starting on setting up Celery
- Imported celery into __init__
- Fixed typos
- Currently blocked on Google OAuth
- Added a comma because tuple
- Make template directories more standard
- Fix Django Admin (somehow)
- Update README.md
- SITE ID WAAHHH
- Try to set up petite vue
- We don't need a counter
- chmod 755 (linux qol)
- django debugging
- bodge command
- The command works
- Some more functionality
- Rename command
- Login redirect to root
- Model database
- Migrations
- Add name to reservation
- Update README.md
- WRONG LINK
- Made navbar
- Bodgey attempt at …

django-simple-history dependency

---

ratatoskr/app/templates/app/layouts/base.html
ratatoskr/app/templates/app/layouts/schedule_base.html
ratatoskr/app/templates/app/pages/index.html
ratatoskr/ratatoskr/threadutil.py
ratatoskr/static/scss/app/darkmode.scss

Tasks spawned by calling a function decorated by `threadpool_decorator` should no longer raise an exception silently. The future returned by `ThreadPoolExecutor.submit` is also returned from the decorated function, which is useful for when you want to call the funcition synchronously.
Dark mode now uses cookies so that we can apply dark styles in the render template. This allows us to add a dark mode style before PetiteVue is fully initalized if the user has a dark preference, preventing them from being flashbanged before the dark mode style can be applied.

`threadpool_decorator` returns future, dark mode adjustments

---

ratatoskr/app/templates/app/layouts/base.html
ratatoskr/app/templates/app/pages/create_schedule.html
ratatoskr/app/templates/app/pages/create_timeslots.html
ratatoskr/app/templates/app/pages/dashboard.html
ratatoskr/app/templates/app/pages/schedule.html
ratatoskr/app/views.py
ratatoskr/static/scss/app/darkmode.scss
ratatoskr/static/scss/app/tiny-mce.scss
ratatoskr/static/scss/app/var-override.scss
ratatoskr/static/scss/style.scss

I also changed "From" and "To" to "Start" and "End" on the website for clarity.

Dark theme improvements, styling fixes

---

ratatoskr/app/templates/app/layouts/schedule_base.html
ratatoskr/app/templates/app/pages/schedule_edit.html

New account using the Ratatoskr email has been created and added to the App Needs document. Will close #181

Change TinyMCE API Key

---

ratatoskr/app/templates/app/pages/help.html

Removed "unnecessary" help cards.

Doing what Seamus told me to do

---

ratatoskr/app/templates/app/layouts/base.html
ratatoskr/app/templates/app/pages/privacy.html
ratatoskr/app/urls.py
ratatoskr/app/views.py

Privacy Policy

---

ratatoskr/app/templates/app/layouts/base.html
ratatoskr/app/templates/app/pages/about.html
ratatoskr/app/templates/app/pages/contact.html
ratatoskr/app/templates/app/pages/help.html
ratatoskr/app/templates/app/pages/index.html
ratatoskr/app/templates/app/pages/privacy.html

Note: Contact page has a placeholder email until SendGrid is set up.

Removed affiliation with Worcester Tech and updated the pages to work with the change.

---

ratatoskr/app/forms.py
ratatoskr/app/templates/app/pages/create_schedule.html

Resolves #197. It seems that `should_lock_automatically` wasn't necessary.

Fixing schedule creation.

---

ratatoskr/app/tokenutil.py

add a function that refreshes a user's socialapp token
next PR will be cost $100

feature: refresh token function
